import { NextResponse } from "next/server"
import { eq } from "drizzle-orm"
import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import {
  db,
  requests,
  requestItems,
  inventoryItems,
  users,
} from "@/lib/db"
import { requireUser, canApproveRequests } from "@/lib/auth"

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const user = await requireUser()

  const [req] = await db
    .select({
      id: requests.id,
      status: requests.status,
      purpose: requests.purpose,
      createdAt: requests.createdAt,
      fulfilledAt: requests.fulfilledAt,
      requesterId: requests.requesterId,
      requesterName: users.fullName,
      requesterEmail: users.email,
      requesterDept: users.department,
    })
    .from(requests)
    .leftJoin(users, eq(requests.requesterId, users.id))
    .where(eq(requests.id, id))
    .limit(1)

  if (!req) return new NextResponse("Not found", { status: 404 })
  if (req.requesterId !== user.id && !canApproveRequests(user.role)) {
    return new NextResponse("Forbidden", { status: 403 })
  }

  const lines = await db
    .select({
      itemName: inventoryItems.name,
      itemSku: inventoryItems.sku,
      unitPrice: inventoryItems.unitPrice,
      quantityRequested: requestItems.quantityRequested,
      quantityFulfilled: requestItems.quantityFulfilled,
    })
    .from(requestItems)
    .leftJoin(inventoryItems, eq(requestItems.itemId, inventoryItems.id))
    .where(eq(requestItems.requestId, id))

  const pdf = await PDFDocument.create()
  const page = pdf.addPage([595, 842]) // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)

  const margin = 48
  let y = 800
  const black = rgb(0.07, 0.07, 0.07)
  const muted = rgb(0.42, 0.42, 0.42)

  page.drawText("Stockroom", { x: margin, y, size: 18, font: bold, color: black })
  page.drawText("Supply Receipt", { x: margin, y: y - 22, size: 11, font, color: muted })
  y -= 60

  const meta = [
    ["Receipt #", req.id.slice(0, 8).toUpperCase()],
    ["Date", new Date(req.fulfilledAt ?? req.createdAt).toLocaleString("en-US")],
    ["Status", req.status],
    ["Requester", req.requesterName ?? req.requesterEmail ?? "—"],
    ["Department", req.requesterDept ?? "—"],
    ["Purpose", req.purpose ?? "—"],
  ]
  for (const [k, v] of meta) {
    page.drawText(k, { x: margin, y, size: 10, font: bold, color: muted })
    page.drawText(String(v), { x: margin + 90, y, size: 10, font, color: black })
    y -= 16
  }

  y -= 14
  page.drawLine({
    start: { x: margin, y },
    end: { x: 595 - margin, y },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  })
  y -= 18

  page.drawText("Item", { x: margin, y, size: 10, font: bold, color: muted })
  page.drawText("SKU", { x: 290, y, size: 10, font: bold, color: muted })
  page.drawText("Qty", { x: 400, y, size: 10, font: bold, color: muted })
  page.drawText("Unit", { x: 440, y, size: 10, font: bold, color: muted })
  page.drawText("Total", { x: 510, y, size: 10, font: bold, color: muted })
  y -= 14
  page.drawLine({
    start: { x: margin, y: y + 6 },
    end: { x: 595 - margin, y: y + 6 },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  })

  let total = 0
  for (const l of lines) {
    const unit = Number.parseFloat(l.unitPrice ?? "0")
    const lineTotal = unit * l.quantityFulfilled
    total += lineTotal
    page.drawText(String(l.itemName ?? "—").slice(0, 36), { x: margin, y, size: 10, font, color: black })
    page.drawText(String(l.itemSku ?? "—"), { x: 290, y, size: 9, font, color: muted })
    page.drawText(String(l.quantityFulfilled), { x: 400, y, size: 10, font, color: black })
    page.drawText(`$${unit.toFixed(2)}`, { x: 440, y, size: 10, font, color: black })
    page.drawText(`$${lineTotal.toFixed(2)}`, { x: 510, y, size: 10, font, color: black })
    y -= 18
    if (y < 100) break
  }

  y -= 8
  page.drawLine({
    start: { x: margin, y },
    end: { x: 595 - margin, y },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  })
  y -= 18
  page.drawText("Total", { x: 440, y, size: 11, font: bold, color: black })
  page.drawText(`$${total.toFixed(2)}`, { x: 510, y, size: 11, font: bold, color: black })

  page.drawText("Generated by Stockroom · This receipt confirms supplies have been issued.", {
    x: margin,
    y: 60,
    size: 9,
    font,
    color: muted,
  })

  const bytes = await pdf.save()
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="receipt-${req.id.slice(0, 8)}.pdf"`,
    },
  })
}
